# Generated by Django 5.2.1 on 2025-05-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='mensagens/')),
                ('agendado_para', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('erro_ultimo_envio', models.TextField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='channels.channel')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_agendadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
