# Generated by Django 5.2.1 on 2025-05-26 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
