# Generated by Django 5.2.1 on 2025-05-26 21:49

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0002_alter_scheduledmessage_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='dias_semana',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Segunda'), ('tue', 'Terça'), ('wed', 'Quarta'), ('thu', 'Quinta'), ('fri', 'Sexta'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='tipo',
            field=models.CharField(choices=[('unico', 'Único'), ('recorrente', 'Recorrente')], default='unico', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='agendado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
