# Generated by Django 5.2.1 on 2025-05-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0003_scheduledmessage_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
