# Generated by Django 5.2.1 on 2025-05-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0004_scheduledmessage_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('emoji', 'Emoji'), ('arquivo', 'Arquivo'), ('audio', 'Áudio'), ('imagem', 'Imagem')], max_length=20)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='blocos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='scheduled_messages.scheduledmessage')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
