# Generated by Django 5.2.1 on 2025-05-27 03:35

import scheduled_messages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0005_messageblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageblock',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=scheduled_messages.models.user_directory_path),
        ),
    ]
