# Generated by Django 5.2.1 on 2025-05-27 03:55

import scheduled_messages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0006_alter_messageblock_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='arquivo_nome_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=scheduled_messages.models.unique_file_path),
        ),
    ]
