# Generated by Django 5.2.1 on 2025-05-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0007_messageblock_arquivo_nome_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessageOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='scheduled_messages.scheduledmessage')),
            ],
            options={
                'verbose_name': 'Ocorrência de Mensagem Recorrente',
                'verbose_name_plural': 'Ocorrências de Mensagens Recorrentes',
                'unique_together': {('mensagem', 'data', 'horario')},
            },
        ),
    ]
