# Generated by Django 5.2.1 on 2025-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0008_scheduledmessageoccurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='enviado',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='erro_ultimo_envio',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='tentativas',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='caption',
            field=models.CharField(blank=True, help_text='Legenda para anexar junto ao arquivo (opcional)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='blocos/'),
        ),
    ]
