# Generated by Django 5.2.1 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0009_remove_scheduledmessage_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='caption',
            field=models.CharField(blank=True, help_text='Legenda para este arquivo (opcional)', max_length=1024, null=True),
        ),
    ]
