# Generated by Django 5.2.1 on 2025-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0010_messageblock_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
