# Generated by Django 5.2.1 on 2025-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0011_scheduledmessage_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageblock',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('emoji', 'Emoji'), ('arquivo', 'Arquivo'), ('audio', 'Áudio'), ('imagem', 'Imagem'), ('inline_keyboard', 'Teclado de Botões (Inline Keyboard)')], max_length=20),
        ),
    ]
