# Generated by Django 5.2.1 on 2025-05-28 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0012_alter_messageblock_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dados', models.JSONField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('descartado', 'Descartado')], default='rascunho', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rascunhos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
