# Generated by Django 5.2.1 on 2025-05-28 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0013_draftmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
