# Generated by Django 5.2.1 on 2025-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_messages', '0014_scheduledmessage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
