# Generated by Django 5.2.1 on 2025-05-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('erro', 'Erro'), ('info', 'Info'), ('warning', 'Warning')], max_length=20)),
                ('mensagem', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
