# Generated by Django 5.2.1 on 2025-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_campos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mensagem_texto',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
