# Generated by Django 5.2.1 on 2025-07-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_log_mensagem_texto'),
        ('scheduled_messages', '0015_messageblock_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduled_messages.scheduledmessage'),
        ),
    ]
