# Generated by Django 5.2.1 on 2025-05-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
    ]
