# Generated by Django 5.2.1 on 2025-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20250527_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Token do Bot do Telegram para este canal', max_length=100, null=True),
        ),
    ]
